package defaults

const (
	DefaultApplicationName        = "gomcp"
	DefaultConfigurationDirectory = ".gomcp"
	DefaultMultiplexerPort        = 8090
	DefaultWsPort                 = 8080
	DefaultProxyConfigPath        = "gomcp-proxy.json"
	DefaultProxyWhatIsThat        = "configuration file for gomcp-proxy. Do NOT edit this file."
	DefaultProxyMoreInfo          = "More information about gomcp-proxy can be found at https://github.com/llmcontext/gomcp"
)
